apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rhbk-demo-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      app: keycloak
  endpoints:
    - port: management
      path: /metrics
      scheme: http
      interval: 30s
