apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  password: rhbk
  username: rhbk