apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-webauthn-setup
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: default
      containers:
      - name: setup-webauthn
        image: badouralix/curl-jq:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          
          echo "Esperando a que Keycloak esté disponible..."
          sleep 30
          
          KEYCLOAK_URL="https://{{ .Values.keycloak.keycloakAppName }}-service:8443"
          ADMIN_USER=$(cat /keycloak-admin/username)
          ADMIN_PASS=$(cat /keycloak-admin/password)
          
          echo "Obteniendo token de acceso..."
          TOKEN=$(curl -sk -X POST "$KEYCLOAK_URL/realms/master/protocol/openid-connect/token" \
            -d "client_id=admin-cli" \
            -d "username=$ADMIN_USER" \
            -d "password=$ADMIN_PASS" \
            -d "grant_type=password" 2>/dev/null | jq -r '.access_token')
          
          if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
            echo "Error: No se pudo obtener token"
            exit 1
          fi
          
          echo "Configurando WebAuthn Passwordless Policy..."
          curl -sk -X PUT -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            "$KEYCLOAK_URL/admin/realms/master" \
            -d '{
              "webAuthnPolicyPasswordlessRpEntityName": "Red Hat Keycloak Demo",
              "webAuthnPolicyPasswordlessSignatureAlgorithms": ["ES256", "RS256"],
              "webAuthnPolicyPasswordlessRpId": "",
              "webAuthnPolicyPasswordlessAttestationConveyancePreference": "none",
              "webAuthnPolicyPasswordlessAuthenticatorAttachment": "platform",
              "webAuthnPolicyPasswordlessRequireResidentKey": "Yes",
              "webAuthnPolicyPasswordlessUserVerificationRequirement": "required",
              "webAuthnPolicyPasswordlessCreateTimeout": 60,
              "webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister": false
            }' 2>/dev/null
          
          echo "Habilitando Required Action para WebAuthn Passwordless..."
          curl -sk -X PUT -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            "$KEYCLOAK_URL/admin/realms/master/authentication/required-actions/webauthn-register-passwordless" \
            -d '{
              "alias": "webauthn-register-passwordless",
              "name": "Webauthn Register Passwordless",
              "providerId": "webauthn-register-passwordless",
              "enabled": true,
              "defaultAction": false,
              "priority": 70,
              "config": {}
            }' 2>/dev/null
          
          echo "Obteniendo ID del Browser Flow..."
          BROWSER_FLOW_ID=$(curl -sk -H "Authorization: Bearer $TOKEN" \
            "$KEYCLOAK_URL/admin/realms/master/authentication/flows" 2>/dev/null | \
            jq -r '.[] | select(.alias=="browser") | .id')
          
          echo "Copiando Browser Flow como browser-webauthn..."
          NEW_FLOW=$(curl -sk -X POST -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            "$KEYCLOAK_URL/admin/realms/master/authentication/flows/$BROWSER_FLOW_ID/copy" \
            -d '{"newName": "browser-webauthn"}' 2>/dev/null)
          
          sleep 2
          
          echo "Obteniendo execuciones del nuevo flow..."
          NEW_FLOW_ID=$(curl -sk -H "Authorization: Bearer $TOKEN" \
            "$KEYCLOAK_URL/admin/realms/master/authentication/flows" 2>/dev/null | \
            jq -r '.[] | select(.alias=="browser-webauthn") | .id')
          
          EXECUTIONS=$(curl -sk -H "Authorization: Bearer $TOKEN" \
            "$KEYCLOAK_URL/admin/realms/master/authentication/flows/$NEW_FLOW_ID/executions" 2>/dev/null)
          
          echo "Buscando la ejecución de 'browser-webauthn forms'..."
          FORMS_EXEC_ID=$(echo "$EXECUTIONS" | jq -r '.[] | select(.displayName=="browser-webauthn forms") | .id')
          
          if [ -n "$FORMS_EXEC_ID" ] && [ "$FORMS_EXEC_ID" != "null" ]; then
            echo "Obteniendo sub-flow de forms..."
            FORMS_FLOW_ID=$(echo "$EXECUTIONS" | jq -r '.[] | select(.displayName=="browser-webauthn forms") | .flowId')
            
            SUBEXECUTIONS=$(curl -sk -H "Authorization: Bearer $TOKEN" \
              "$KEYCLOAK_URL/admin/realms/master/authentication/flows/$FORMS_FLOW_ID/executions" 2>/dev/null)
            
            echo "Buscando execution de 'browser-webauthn Browser - Conditional OTP'..."
            OTP_EXEC_ID=$(echo "$SUBEXECUTIONS" | jq -r '.[] | select(.displayName | contains("Conditional OTP")) | .id')
            
            if [ -n "$OTP_EXEC_ID" ] && [ "$OTP_EXEC_ID" != "null" ]; then
              echo "Agregando WebAuthn Passwordless al flow..."
              curl -sk -X POST -H "Authorization: Bearer $TOKEN" \
                -H "Content-Type: application/json" \
                "$KEYCLOAK_URL/admin/realms/master/authentication/flows/$FORMS_FLOW_ID/executions/execution" \
                -d '{
                  "provider": "webauthn-authenticator-passwordless"
                }' 2>/dev/null
              
              sleep 2
              
              echo "Configurando WebAuthn como ALTERNATIVE..."
              SUBEXECUTIONS_NEW=$(curl -sk -H "Authorization: Bearer $TOKEN" \
                "$KEYCLOAK_URL/admin/realms/master/authentication/flows/$FORMS_FLOW_ID/executions" 2>/dev/null)
              
              WEBAUTHN_EXEC_ID=$(echo "$SUBEXECUTIONS_NEW" | jq -r '.[] | select(.providerId=="webauthn-authenticator-passwordless") | .id')
              
              if [ -n "$WEBAUTHN_EXEC_ID" ] && [ "$WEBAUTHN_EXEC_ID" != "null" ]; then
                curl -sk -X PUT -H "Authorization: Bearer $TOKEN" \
                  -H "Content-Type: application/json" \
                  "$KEYCLOAK_URL/admin/realms/master/authentication/flows/$FORMS_FLOW_ID/executions" \
                  -d "{
                    \"id\": \"$WEBAUTHN_EXEC_ID\",
                    \"requirement\": \"ALTERNATIVE\"
                  }" 2>/dev/null
              fi
            fi
          fi
          
          echo "Configurando browser-webauthn como Browser Flow por defecto..."
          curl -sk -X PUT -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            "$KEYCLOAK_URL/admin/realms/master" \
            -d '{
              "browserFlow": "browser-webauthn"
            }' 2>/dev/null
          
          echo "✅ WebAuthn Passwordless configurado exitosamente!"
        volumeMounts:
        - name: keycloak-admin
          mountPath: /keycloak-admin
          readOnly: true
      volumes:
      - name: keycloak-admin
        secret:
          secretName: {{ .Values.keycloak.keycloakAppName }}-initial-admin
