apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  labels:
    app.openshift.io/runtime: postgresql
spec:
  serviceName: postgresql-service
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql-db
          image: registry.redhat.io/rhel9/postgresql-15:latest
          volumeMounts:
            - mountPath: /data
              name: cache-volume
          env:
            - name: POSTGRESQL_USER
              value: rhbk
            - name: POSTGRESQL_PASSWORD
              value: rhbk
            - name: POSTGRESQL_DATABASE
              value: rhbk
      volumes:
        - name: cache-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
