apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: rhbk-demo
spec:
  instances: 1
  externalAccess:
    enabled: true
  externalDatabase:
    enabled: true
  postgresql:
    host: postgresql
    database: rhbk
    username: rhbk
    password: rhbk
