apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    dashboards: "grafana"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  serviceAccount:
    metadata:
      annotations:
        serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-route"}}'
  deployment:
    spec:
      template:
        spec:
          serviceAccountName: grafana-serviceaccount
  client:
    preferService: true
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: admin
      admin_password: admin
