apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    dashboards: "grafana"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: admin
      admin_password: admin
