apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: webauthn-passwordless-flow
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  keycloakCRName: {{ .Values.keycloak.keycloakAppName }}
  realm:
    id: master
    realm: master
    enabled: true
    # Configuración de WebAuthn Passwordless
    webAuthnPolicyPasswordlessRpEntityName: "Red Hat Keycloak Demo"
    webAuthnPolicyPasswordlessSignatureAlgorithms:
      - ES256
      - RS256
    webAuthnPolicyPasswordlessRpId: ""
    webAuthnPolicyPasswordlessAttestationConveyancePreference: "none"
    webAuthnPolicyPasswordlessAuthenticatorAttachment: "platform"
    webAuthnPolicyPasswordlessRequireResidentKey: "Yes"
    webAuthnPolicyPasswordlessUserVerificationRequirement: "required"
    webAuthnPolicyPasswordlessCreateTimeout: 60
    webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister: false
    webAuthnPolicyPasswordlessAcceptableAaguids: []
    # Browser Flow con WebAuthn Passwordless
    authenticationFlows:
      - alias: "browser-passwordless"
        description: "Browser flow with passwordless WebAuthn authentication"
        providerId: "basic-flow"
        topLevel: true
        builtIn: false
        authenticationExecutions:
          - authenticator: "auth-cookie"
            requirement: "ALTERNATIVE"
            priority: 10
            authenticatorFlow: false
          - authenticator: "identity-provider-redirector"
            requirement: "ALTERNATIVE"
            priority: 20
            authenticatorFlow: false
          - requirement: "ALTERNATIVE"
            priority: 30
            flowAlias: "browser-passwordless-forms"
            authenticatorFlow: true
      - alias: "browser-passwordless-forms"
        description: "Username and passwordless WebAuthn"
        providerId: "basic-flow"
        topLevel: false
        builtIn: false
        authenticationExecutions:
          - authenticator: "auth-username-form"
            requirement: "REQUIRED"
            priority: 10
            authenticatorFlow: false
          - requirement: "REQUIRED"
            priority: 20
            flowAlias: "browser-passwordless-authentication"
            authenticatorFlow: true
      - alias: "browser-passwordless-authentication"
        description: "Passwordless authentication methods"
        providerId: "basic-flow"
        topLevel: false
        builtIn: false
        authenticationExecutions:
          - authenticator: "webauthn-authenticator-passwordless"
            requirement: "ALTERNATIVE"
            priority: 10
            authenticatorFlow: false
          - authenticator: "auth-password-form"
            requirement: "ALTERNATIVE"
            priority: 20
            authenticatorFlow: false
    # Configuración de autenticación requerida
    requiredActions:
      - alias: "webauthn-register-passwordless"
        name: "Webauthn Register Passwordless"
        providerId: "webauthn-register-passwordless"
        enabled: true
        defaultAction: true
        priority: 70
        config: {}
    # Configurar el browser flow por defecto
    browserFlow: "browser-passwordless"
