apiVersion: v1
kind: Namespace
metadata:
  name: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: grafana-operator-og
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: v5
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
